#!/usr/bin/env bash
# nginx must be running as nginx user
pkill -f apache2
chmod 644 /etc/nginx/nginx.conf
sed -i -e 's/80/8080 default_server/g' -e '1 i user nginx;' /etc/nginx/sites-available/default /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
